import fs from 'node:fs';
import path from 'node:path';
import { registry } from '../src/endpoints/registry';
import { toMeta } from '../src/endpoints/types';

const outputPath = path.resolve(
  __dirname,
  '..',
  '..',
  'web',
  'src',
  'generated',
  'endpointMeta.ts',
);
const endpointMetadata = registry.map(toMeta);
const source = `// Generated by server/scripts/generateWebMeta.ts. Do not edit.
import type { EndpointMeta } from '../types/meta';

export const endpointMetadata: EndpointMeta[] = ${JSON.stringify(endpointMetadata, null, 2)};
`;

fs.mkdirSync(path.dirname(outputPath), { recursive: true });
fs.writeFileSync(outputPath, source, 'utf8');
console.log(`Generated ${endpointMetadata.length} endpoint definitions for the web build.`);
